definitions:
  model.Cart:
    properties:
      amount:
        type: number
      isCheckout:
        type: boolean
      products:
        items:
          $ref: '#/definitions/model.CartProduct'
        type: array
      userID:
        type: integer
    type: object
  model.CartProduct:
    properties:
      cartID:
        type: integer
      product:
        $ref: '#/definitions/model.Product'
        type: object
      productID:
        type: integer
      quantity:
        type: integer
    type: object
  model.Product:
    properties:
      inventory:
        type: integer
      name:
        type: string
      price:
        type: number
    type: object
info:
  contact: {}
  license: {}
  title: Swagger API
  version: 0.0.1
paths:
  /api/cart/:
    get:
      description: 獲得Cart
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Cart'
      summary: Get Cart
      tags:
      - cart
    put:
      description: 更新Cart
      parameters:
      - description: 要更新的cart
        in: body
        name: cart
        required: true
        schema:
          $ref: '#/definitions/model.Cart'
      produces:
      - application/json
      responses:
        "200": {}
      summary: Update Cart
      tags:
      - cart
  /api/cart/checkout:
    post:
      description: Cart 結帳
      produces:
      - application/json
      responses:
        "200": {}
      summary: checkout Cart
      tags:
      - cart
  /api/product/:
    get:
      description: 獲得products list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Product'
            type: array
      summary: Get Product list
      tags:
      - product
schemes:
- http
swagger: "2.0"
